constructor {
  Create : ();
};

service P2PvpnContract {
  /// Fetch the VPN configuration file for a given provider.
  FetchProviderFile : (provider: [u8, 32]) -> struct { str, str };
  /// Fetch the list of available VPN providers.
  FetchProviders : () -> vec struct { [u8, 32], str };
  /// Rank a provider positively or negatively after a connection attempt.
  RankProvider : (provider: [u8, 32], good: bool) -> null;
};

