// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ShadowsproutContractClientProgram;
impl sails_rs::client::Program for ShadowsproutContractClientProgram {}
pub trait ShadowsproutContractClient {
    type Env: sails_rs::client::GearEnv;
    fn shadowsprout_contract(
        &self,
    ) -> sails_rs::client::Service<shadowsprout_contract::ShadowsproutContractImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ShadowsproutContractClient
    for sails_rs::client::Actor<ShadowsproutContractClientProgram, E>
{
    type Env = E;
    fn shadowsprout_contract(
        &self,
    ) -> sails_rs::client::Service<shadowsprout_contract::ShadowsproutContractImpl, Self::Env> {
        self.service(stringify!(ShadowsproutContract))
    }
}
pub trait ShadowsproutContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<ShadowsproutContractClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ShadowsproutContractClientCtors
    for sails_rs::client::Deployment<ShadowsproutContractClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<ShadowsproutContractClientProgram, io::Create, Self::Env>
    {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod shadowsprout_contract {
    use super::*;
    pub trait ShadowsproutContract {
        type Env: sails_rs::client::GearEnv;
        /// Add a new VPN provider file.
        fn add_provider_file(
            &mut self,
            provider: [u8; 32],
            name: String,
            kind: String,
            config: String,
        ) -> sails_rs::client::PendingCall<io::AddProviderFile, Self::Env>;
        /// Fetch the VPN configuration file for a given provider.
        fn fetch_provider_file(
            &mut self,
            provider: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::FetchProviderFile, Self::Env>;
        /// Fetch the list of available VPN providers.
        fn fetch_providers(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FetchProviders, Self::Env>;
        /// Rank a provider positively or negatively after a connection attempt.
        fn rank_provider(
            &mut self,
            provider: [u8; 32],
            good: bool,
        ) -> sails_rs::client::PendingCall<io::RankProvider, Self::Env>;
    }
    pub struct ShadowsproutContractImpl;
    impl<E: sails_rs::client::GearEnv> ShadowsproutContract
        for sails_rs::client::Service<ShadowsproutContractImpl, E>
    {
        type Env = E;
        fn add_provider_file(
            &mut self,
            provider: [u8; 32],
            name: String,
            kind: String,
            config: String,
        ) -> sails_rs::client::PendingCall<io::AddProviderFile, Self::Env> {
            self.pending_call((provider, name, kind, config))
        }
        fn fetch_provider_file(
            &mut self,
            provider: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::FetchProviderFile, Self::Env> {
            self.pending_call((provider,))
        }
        fn fetch_providers(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::FetchProviders, Self::Env> {
            self.pending_call(())
        }
        fn rank_provider(
            &mut self,
            provider: [u8; 32],
            good: bool,
        ) -> sails_rs::client::PendingCall<io::RankProvider, Self::Env> {
            self.pending_call((provider, good))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AddProviderFile (provider: [u8; 32], name: String, kind: String, config: String) -> bool);
        sails_rs::io_struct_impl!(FetchProviderFile (provider: [u8; 32]) -> (String,String,));
        sails_rs::io_struct_impl!(FetchProviders () -> Vec<([u8; 32],String,i32,)>);
        sails_rs::io_struct_impl!(RankProvider (provider: [u8; 32], good: bool) -> ());
    }
}
